title: dailydevs.hu
email: your-email@example.com
description: >-
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://dailydevs.hu"

theme: minima

collections:
    authors:
        output: true

permalink: /:collection/:name/

pagination:
    enabled: true
    per_page: 15
    permalink: '/page/:num/'
    title: ' - :num'
    limit: 0
    sort_field: 'date'
    sort_reverse: true

plugins:
    - jekyll-feed
    - jekyll-paginate-v2

exclude:
    - docker
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/
    - package.json
    - package-lock.json
    - webpack.config.js
    - README.md
