title: dailydevs.hu
description: Minden, ami fejleszt√©s...
url: "https://dailydevs.hu"
baseurl: ""

source: ./source/
destination: ./public

collections:
    sections:
        output: true
        permalink: /:name:output_ext
    users:
        output: false
        permalink: /users/:name:output_ext
    categories:
        output: true
        permalink: /categories/:name:output_ext
    tags:
        output: true
        permalink: /tags/:name:output_ext
    posts:
        output: true
        permalink: /posts/:year/:month/:day/:title:output_ext

defaults:
    - scope:
          path: ""
          type: "users"
      values:
          layout: "user"
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
    - scope:
          path: ""
          type: "sections"
      values:
          layout: "collection"
    - scope:
          path: ""
          type: "categories"
      values:
          layout: "collection"
    - scope:
          path: ""
          type: "tags"
      values:
          layout: "collection"
    - scope:
          path: ""
      values:
          layout: "default"
    - scope:
          path: "assets/images"
      values:
          image: true

pagination:
    enabled: true
    per_page: 10
    permalink: '/page/:num/'
    title: ' - :num'
    limit: 0
    sort_field: 'date'
    sort_reverse: true

plugins:
    - jekyll-paginate-v2

exclude:
    - .gitkeep
    - .sass-cache/
    - .jekyll-cache/

kramdown:
    syntax_highlighter_opts:
        disable: true
